# Generated by Django 4.2.4 on 2023-09-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
