# Generated by Django 4.2.4 on 2023-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_curso_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ('nombre', 'profesion'), 'verbose_name': 'Profesor', 'verbose_name_plural': 'The Profesors'},
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profesion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profesor',
            unique_together={('nombre', 'apellido')},
        ),
    ]
