# Generated by Django 4.2.4 on 2023-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_entregable'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='link',
            field=models.CharField(max_length=265, null=True),
        ),
    ]
